# Run Information
api-version: "1.16"
main: com.firecontroller1847.dynmapps.DynmapPS
depend: [dynmap, PreciousStones]
softdepend: [SimpleClans]

  # Metadata Information
name: ${project.name}
version: ${project.version}
author: FireController#1847
website: https://www.visualfiredev.com/